---
title: Hernoem een ​​sprite in Scratch
hero_image: images / banner.png
description: Hernoem een ​​sprite in Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rood
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: maker, ontwerp-0, programmeren-0, phys-comp-0, productie-0, community-0
interests: ""
technologies: "krassen"
steps:
  - 
    title: Hernoem een ​​sprite
