---
title: Переименуйте спрайт в Scratch
hero_image: Изображения / banner.png
description: Переименуйте спрайт в Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: красный
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: создатель, дизайн-0, программирование-0, физика-комп-0, производство-0, сообщество-0
interests: ""
technologies: "царапина"
steps:
  - 
    title: Переименовать спрайт
