---
title: Gi nytt navn til en sprite i Scratch
hero_image: images / banner.png
description: Gi nytt navn til en sprite i Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaperen, design-0, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
interests: ""
technologies: "ripe"
steps:
  - 
    title: Gi nytt navn til en sprite
