---
title: Đổi tên một sprite trong Scratch
hero_image: images / banner.png
description: Đổi tên một sprite trong Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: đỏ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tác giả, thiết kế-0, lập trình-0, phys-comp-0, sản xuất-0, cộng đồng-0
interests: ""
technologies: "vết trầy"
steps:
  - 
    title: Đổi tên một sprite
