---
title: Omdøb et sprite i Scratch
hero_image: images/banner.png
description: Omdøb et sprite i Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: ""
technologies: "scratch"
steps:
  - 
    title: Omdøb et sprite
