---
title: Renomear um sprite no Scratch
hero_image: images / banner.png
description: Renomeie um sprite no Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "coçar, arranhão"
steps:
  - 
    title: Renomeie um sprite
