---
title: Преименувайте Sprite в Scratch
hero_image: изображения / banner.png
description: Преименувайте Sprite в Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: червен
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: създател, дизайн-0, програмиране-0, phys-comp-0, производство-0, общност-0
interests: ""
technologies: "драскотина"
steps:
  - 
    title: Преименувайте спрайт
