---
title: Preimenuj lika u Scratchu
hero_image: images/banner.png
description: Preimenuj lika u Scratchu
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: Crvena
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: kreator, dizajn-0, programiranje-0, fiz-comp-0, proizvodnja-0, community-0
interests: ""
technologies: "ogrepsti"
steps:
  - 
    title: Preimenujte sprite
