---
title: Nimeä uusi sprite tyhjäksi
hero_image: Kuvien / banner.png
description: Nimeä uusi sprite tyhjäksi
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: punainen
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: luoja, design-0, ohjelmointi-0, phys-comp-0, valmistus-0, yhteisö-0
interests: ""
technologies: "naarmu"
steps:
  - 
    title: Nimeä uudelleen sprite
