---
title: تغییر نام شبح در اسکرچ
hero_image: images/banner.png
description: تغییر نام شبح در اسکرچ
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
steps:
  - itle: تغییر نام شبح
