---
title: تغییر نام پیمایش در ابتدا
hero_image: images / banner.png
description: تغییر نام پیمایش در ابتدا
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: سرخ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: خالق، طراحی 0، برنامه نویسی 0، فیزیک کامپوننت 0، تولید 0، جامعه 0
interests: ""
technologies: "خراش"
steps:
  - 
    title: نام مستعار را تغییر دهید
