---
title: Cambiar el nombre de un sprite en Scratch
hero_image: images / banner.png
description: Cambiar el nombre de un sprite en Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, dise침o-0, programaci칩n-0, phys-comp-0, fabricaci칩n-0, comunidad-0
interests: ""
technologies: "rasgu침o"
steps:
  - 
    title: Cambiar el nombre de un sprite
