---
title: Ail-enwi swite yn Scratch
hero_image: delweddau / banner.png
description: Ail-enwi swite yn Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: Coch
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: crewr, dylunio-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "crafu"
steps:
  - 
    title: Ail-enwi swite
