---
title: Benennen Sie ein Sprite in Scratch um
hero_image: Bilder / Banner.png
description: Benennen Sie ein Sprite in Scratch um
original_url: https://codeclubprojects.org/de-DE/scratch/rock-band
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: ""
technologies: "kratzen"
steps:
  - 
    title: Benennen Sie ein Sprite um
