---
title: Redenumiți un sprite în Scratch
hero_image: images / banner.png
description: Redenumiți un sprite în Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: roșu
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: ""
technologies: "zgârietură"
steps:
  - 
    title: Redenumiți un sprite
