---
title: Renomeie um sprite no Scratch
hero_image: images/banner.png
description: Renomeie um sprite no Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, desenhar-0, programação-0, computação física-0, fabricação-0, comunidade-0
interests: ""
technologies: "scratch"
steps:
  - 
    title: Renomear um sprite
