---
title: Ganti nama sprite di Scratch
hero_image: images / banner.png
description: Ganti nama sprite di Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, desain-0, pemrograman-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: "scratch"
steps:
  - 
    title: Mengganti nama sprite
