---
title: Canvieu el nom d'un sprite a Scratch
hero_image: imatges / banner.png
description: Canvieu el nom d'un sprite a Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: vermell
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, disseny-0, programació-0, phys-comp-0, fabricació-0, comunitat-0
interests: ""
technologies: "rascar"
steps:
  - 
    title: Canvieu el nom d'un sprite
