---
title: Preimenuj sprite v Scratch
hero_image: images / banner.png
description: Preimenuj sprite v Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: ustvarjalec, design-0, programiranje-0, fiz-comp-0, izdelava-0, skupnost-0
interests: ""
technologies: "praska"
steps:
  - 
    title: Preimenuj sprite
