---
title: Přejmenujte sprite v aplikaci Scratch
hero_image: obrázky / banner.png
description: Přejmenujte sprite v aplikaci Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: Červené
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tvůrce, design-0, programování-0, phys-comp-0, výroba-0, komunita-0
interests: ""
technologies: "poškrábat"
steps:
  - 
    title: Přejmenujte sprite
