---
title: Nevezzen át egy spriteet a Scratch-ban
hero_image: images / banner.png
description: Nevezzen át egy spriteet a Scratch-ban
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: piros
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: alkotó, design-0, programozás-0, fiz-comp-0, gyártás-0, community-0
interests: ""
technologies: "karcolás"
steps:
  - 
    title: Nevezzen át egy sprite-et
