---
title: Zmień nazwę ikonki w Scratch
hero_image: images / banner.png
description: Zmień nazwę ikonki w Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: czerwony
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
interests: ""
technologies: "zadraśnięcie"
steps:
  - 
    title: Zmień nazwę ikonki
