---
title: Premenujte sprite na Scratch
hero_image: images / banner.png
description: Premenujte sprite na Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: červená
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tvorca, dizajn-0, programovanie-0, phys-comp-0, výroba-0, komunita-0
interests: ""
technologies: "škrabanec"
steps:
  - 
    title: Premenujte sprite
