---
title: Byt namn på en sprite i Scratch
hero_image: images / banner.png
description: Byt namn på en sprite i Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: röd
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skapare, design-0, programmering-0, phys-comp-0, tillverkning-0, community-0
interests: ""
technologies: "repa"
steps:
  - 
    title: Byt namn på en sprite
