---
title: Namakan semula sprite dalam Scratch
hero_image: imej / banner.png
description: Namakan semula sprite dalam Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, reka bentuk-0, pengaturcaraan-0, phys-comp-0, pembuatan-0, komuniti-0
interests: ""
technologies: "awal"
steps:
  - 
    title: Namakan semula sprite
