---
title: Rinominare uno sprite in Scratch
hero_image: images / banner.png
description: Rinominare uno sprite in Scratch
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: rosso
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creatore, design-0, programmazione-0, compatta-0, fabbricazione-0, comunità-0
interests: ""
technologies: "graffiare"
steps:
  - 
    title: Rinominare uno sprite
