---
title: Scratch'te hareketli grafiği yeniden adlandır
hero_image: images / banner.png
description: Scratch'te hareketli grafiği yeniden adlandır
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: kırmızı
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programlama-0, fiz-comp-0, production-0, topluluk-0
interests: ""
technologies: "çizik"
steps:
  - 
    title: Bir hareketli grafiği yeniden adlandır
